create table if not exists "t_settings"
(
    ID      bigint generated by default as identity,
    "key"   varchar,
    "value" varchar,
    unique ("key"),
    primary key (ID)
);

create table if not exists "t_catalog_subtype"
(
    SUBTYPE_ID      bigint generated by default as identity,
    "name"          varchar,
    CATALOG_SUBTYPE bigint,
    primary key (SUBTYPE_ID)
);

create table if not exists "t_catalog_details"
(
    ID              bigint generated by default as identity,
    "name"          varchar,
    SUBTYPE_ID      bigint default null,
    CATALOG_SUBTYPE bigint,
    primary key (ID),
    constraint "subtype_id_fk"
        foreign key (SUBTYPE_ID)
            references "t_catalog_subtype" (SUBTYPE_ID)
);

create table if not exists "t_call_history"
(
    ID                bigint generated by default as identity,
    "phone"           varchar,
    "create_datetime" datetime,
    "date"            datetime,
    "subtype_id"      bigint,
    "details_id"      bigint,
    "terminal_id"     varchar,
    "title"           varchar,
    "manually"        boolean,
    primary key (ID)
);